"""
modules/ai_content.py
Uses Google Gemini to generate:
  - Top 3 AI tools for daily productivity
  - Latest AI news summary

AI model rankings are computed by ai_ranker.py (weighted benchmark scoring),
NOT generated by the LLM — ensuring reproducible, data-driven results.
"""

import os
import json
import re
from datetime import datetime
import google.generativeai as genai
from modules import logger

GEMINI_KEY = os.getenv("GEMINI_API_KEY", "YOUR_GEMINI_API_KEY_HERE")


def _get_model():
    genai.configure(api_key=GEMINI_KEY)
    return genai.GenerativeModel(
        model_name="gemini-1.5-flash",
        generation_config=genai.GenerationConfig(
            temperature=0.7,
            max_output_tokens=2048,
        ),
        system_instruction=(
            "You are AIPulse, an expert AI industry analyst. "
            "You provide concise, accurate, and insightful daily briefings on AI developments. "
            "Always respond in valid JSON when asked. Be specific with real product names and version numbers."
        ),
    )


def get_daily_ai_content() -> dict:
    """
    Returns a structured dict with:
      - news_summary: str (3-4 sentence overview)
      - top_tools: list of 3 {name, tagline, use_case, url}
      - ai_rankings: list of 3 — computed by ai_ranker (weighted benchmark scores)
    """
    from modules.ai_ranker import get_top3_ranked

    logger.info("ai_content", "Generating daily AI content...")

    # Rankings are ALWAYS calculated — independent of Gemini availability
    try:
        ai_rankings = get_top3_ranked()
        logger.info("ai_content", f"Rankings computed: #{1} {ai_rankings[0]['model']} ({ai_rankings[0]['composite']:.1f})")
    except Exception as e:
        logger.error("ai_content", "Failed to compute AI rankings", exc=e)
        ai_rankings = []

    if GEMINI_KEY == "YOUR_GEMINI_API_KEY_HERE":
        logger.warning("ai_content", "GEMINI_API_KEY not set — using mock news + tools")
        mock = _mock_content()
        mock["ai_rankings"] = ai_rankings
        return mock

    try:
        model  = _get_model()
        today  = datetime.now().strftime("%B %d, %Y")
        prompt = f"""
Today is {today}. Generate a daily AI briefing. Respond ONLY with valid JSON, no markdown, no extra text.

Format:
{{
  "news_summary": "3-4 sentence overview of the most important AI news and developments happening right now",
  "top_tools": [
    {{
      "rank": 1,
      "name": "Tool Name",
      "tagline": "One-line pitch",
      "use_case": "2-3 sentence description of how it helps with day-to-day AI work",
      "category": "Category (e.g. Coding, Writing, Research, Image Gen)",
      "free_tier": true,
      "url": "https://..."
    }}
  ]
}}

Include exactly 3 items in top_tools.
Focus on tools people can use TODAY to be more productive with AI.
"""
        response = model.generate_content(prompt)
        text     = response.text.strip()
        text     = re.sub(r"^```json\s*", "", text)
        text     = re.sub(r"```$", "", text).strip()
        parsed   = json.loads(text)

        # Inject calculated rankings
        parsed["ai_rankings"] = ai_rankings
        logger.info("ai_content", "Daily content generated successfully")
        return parsed

    except Exception as e:
        logger.error("ai_content", "Gemini content generation failed", exc=e)
        mock = _mock_content()
        mock["ai_rankings"] = ai_rankings
        return mock


def chat_with_ai(conversation_history: list, user_message: str) -> str:
    """
    Multi-turn chat with AIPulse bot.
    conversation_history: list of {"role": "user"|"model", "parts": [str]}
    Automatically injects live ranking data when user asks about rankings.
    """
    logger.info("ai_content", f"Chat message received: {user_message[:80]}")

    # Detect ranking questions — inject live calculated data
    ranking_keywords = ["rank", "ranking", "best ai", "top ai", "leaderboard",
                        "score", "which model", "compare model", "vs gpt", "vs claude",
                        "vs gemini", "winning", "leading"]
    wants_ranking = any(kw in user_message.lower() for kw in ranking_keywords)

    ranking_context = ""
    if wants_ranking:
        try:
            from modules.ai_ranker import get_ranking_leaderboard_text, get_top3_ranked
            ranking_context = (
                "\n\n[LIVE CALCULATED RANKINGS — use this data in your response]\n"
                + get_ranking_leaderboard_text()
                + "\n\nThese rankings are computed using a weighted scoring engine across 8 dimensions: "
                "Reasoning (22%), Coding (18%), Context Window (12%), Speed (12%), Cost Efficiency (10%), "
                "Multimodal (10%), Safety/Alignment (8%), Community (8%)."
            )
            logger.info("ai_content", "Injected live ranking data into chat context")
        except Exception as e:
            logger.error("ai_content", "Failed to inject ranking data into chat", exc=e)

    if GEMINI_KEY == "YOUR_GEMINI_API_KEY_HERE":
        if wants_ranking:
            from modules.ai_ranker import get_ranking_leaderboard_text
            return (
                "⚠️ Gemini key not set (demo mode), but here are the **live calculated rankings**:\n\n"
                f"```\n{get_ranking_leaderboard_text()}\n```\n\n"
                "Rankings are computed from real benchmark data across 8 weighted dimensions."
            )
        return (
            "⚠️ Gemini API key not set. Add your GEMINI_API_KEY to the environment variables. "
            "Stock charts and email are still fully functional!"
        )

    try:
        model    = _get_model()
        chat     = model.start_chat(history=conversation_history)
        full_msg = (
            f"User question: {user_message}"
            + ranking_context
            + "\n\nAnswer helpfully and concisely. If the user asks about stocks or market data, "
            "mention they can check the Stock Charts tab for live data."
        )
        response = chat.send_message(full_msg)
        logger.debug("ai_content", f"Chat response generated ({len(response.text)} chars)")
        return response.text
    except Exception as e:
        logger.error("ai_content", "Chat response failed", exc=e)
        return f"⚠️ Error reaching Gemini: {str(e)}"


def get_email_subject(content: dict) -> str:
    """Generate a punchy email subject line."""
    if GEMINI_KEY == "YOUR_GEMINI_API_KEY_HERE":
        return f"⚡ AIPulse Daily Briefing — {datetime.now().strftime('%b %d')}"
    try:
        model    = _get_model()
        top_tool = content.get("top_tools", [{}])[0].get("name", "AI")
        rankings = content.get("ai_rankings", [])
        top_model = rankings[0].get("model", "GPT-4o") if rankings else "GPT-4o"
        resp = model.generate_content(
            f"Write a punchy email subject line for a daily AI newsletter. "
            f"Today's top tool is {top_tool} and the #1 ranked AI is {top_model}. "
            f"Max 60 chars. No quotes. Just the subject line."
        )
        subject = resp.text.strip()[:80]
        logger.info("ai_content", f"Subject line generated: {subject}")
        return subject
    except Exception as e:
        logger.warning("ai_content", f"Subject line generation failed: {e}")
        return f"⚡ AIPulse Daily Briefing — {datetime.now().strftime('%b %d')}"


# ── Mock content (no API key) ──────────────────────────────────────────────────

def _mock_content() -> dict:
    """Mock news + tools only. Rankings are always computed by ai_ranker."""
    return {
        "news_summary": (
            "OpenAI continues to dominate headlines with GPT-4o updates improving real-time voice "
            "and vision capabilities. Google DeepMind's Gemini 1.5 Pro has expanded context windows "
            "to 2M tokens, enabling unprecedented document analysis. Anthropic released Claude 3.5 Sonnet "
            "with major coding benchmark improvements, while Meta's Llama 3 open-source models push "
            "the frontier for local deployment."
        ),
        "top_tools": [
            {
                "rank": 1,
                "name": "Cursor",
                "tagline": "The AI-first code editor",
                "use_case": (
                    "Cursor integrates Claude and GPT-4 directly into your IDE, letting you write, "
                    "refactor, and debug code with natural language. Tab-complete entire functions "
                    "and chat with your codebase instantly."
                ),
                "category": "Coding",
                "free_tier": True,
                "url": "https://cursor.so",
            },
            {
                "rank": 2,
                "name": "Perplexity AI",
                "tagline": "Answer engine for the real world",
                "use_case": (
                    "Perplexity replaces traditional search with AI-synthesized answers backed by "
                    "real-time web sources. Perfect for research, fact-checking, and staying current "
                    "on rapidly evolving topics like AI news."
                ),
                "category": "Research",
                "free_tier": True,
                "url": "https://perplexity.ai",
            },
            {
                "rank": 3,
                "name": "Runway Gen-3",
                "tagline": "Professional AI video generation",
                "use_case": (
                    "Runway's Gen-3 Alpha produces cinematic AI video from text or image prompts. "
                    "Ideal for marketers, creators, and developers needing high-quality video assets "
                    "without a production crew."
                ),
                "category": "Video / Creative",
                "free_tier": True,
                "url": "https://runwayml.com",
            },
        ],
        "ai_rankings": [],  # populated by get_daily_ai_content() via ai_ranker
    }
